apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-auth-service-config
  labels:
    app: {{ .Release.Name }}-auth-service
data:
  MONGO_HOST: {{ .Values.config.mongoHost | quote }}
  MONGO_PORT: {{ .Values.config.mongoPort | quote }}
  MONGO_DB: {{ .Values.config.mongoDB | quote }}
  MONGO_AUTH_DB: {{ .Values.config.mongoAuthDB | quote }}
  MONGO_SSL_ENABLED: {{ .Values.config.mongoSslEnabled | default "false" | quote }}
  VAULT_URI: {{ .Values.config.vaultUri | quote }}
  VAULT_ROLE: {{ printf "%s-auth-service" .Release.Name | quote }}
  VAULT_KV_MOUNT: {{ .Values.config.vaultKvMount | quote }}
  VAULT_SECRET_PATH: {{ .Values.config.vaultSecretPath | quote }}
  AUTH_SERVER_ISSUER: {{ .Values.config.authServerIssuer | quote }}
  OAUTH2_REDIRECT_URI: {{ .Values.config.oauth2RedirectUri | quote }}
  OAUTH2_POST_LOGOUT_REDIRECT_URI: {{ .Values.config.oauth2PostLogoutRedirectUri | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.config.corsAllowedOrigins | quote }}
  ACCESS_TOKEN_TTL: {{ .Values.config.accessTokenTtl | quote }}

