apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-service-secret
  labels:
    app: {{ .Release.Name }}-auth-service
type: Opaque
stringData:
  MONGO_USER: {{ .Values.secrets.mongoUser | quote }}
  MONGO_PASS: {{ .Values.secrets.mongoPass | quote }}
  VAULT_TOKEN: {{ .Values.secrets.vaultToken | quote }}
  OAUTH2_CLIENT_ID: {{ .Values.secrets.oauth2ClientId | quote }}

