apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-project-service-config
  labels:
    app: {{ .Release.Name }}-project-service
data:
  DB_URL: {{ .Values.config.dbUrl | quote }}
  VAULT_URI: {{ .Values.config.vaultUri | quote }}
  VAULT_KV_MOUNT: {{ .Values.config.vaultKvMount | quote }}
  VAULT_SECRET_PATH: {{ .Values.config.vaultSecretPath | quote }}
  AUTH_SERVER_ISSUER: {{ .Values.config.authServerIssuer | quote }}
  AUTH_SERVER_JWK_SET_URI: {{ .Values.config.authServerJwkSetUri | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.config.corsAllowedOrigins | quote }}

