apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-project-service-secret
  labels:
    app: {{ .Release.Name }}-project-service
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.dbUser | quote }}
  DB_PASS: {{ .Values.secrets.dbPass | quote }}

