spring:
  application:
    name: auth-service
  mongodb:
    username: ${MONGO_USER}
    password: ${MONGO_PASS}
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT:27017}
    database: ${MONGO_DB:time-tracking}
    authentication-database: ${MONGO_AUTH_DB:admin}
    representation:
      uuid: standard
    ssl:
      enabled: { MONGO_SSL_ENABLED:false }

  cloud:
    vault:
      uri: ${VAULT_URI}
      scheme: https
      authentication: KUBERNETES
      kubernetes:
        role: ${VAULT_ROLE:auth-service}
        service-account-token-file: /var/run/secrets/kubernetes.io/serviceaccount/token

oauth2:
  internal:
    issuer: ${AUTH_SERVER_ISSUER:http://localhost:8080}
    client:
      id: ${OAUTH2_CLIENT_ID}
      redirect-uri: ${OAUTH2_REDIRECT_URI}
      post-logout-redirect-uri: ${OAUTH2_POST_LOGOUT_REDIRECT_URI}
    token:
      access-token-ttl: ${ACCESS_TOKEN_TTL:PT1H}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type,X-Requested-With
  exposed-headers: ""
  allow-credentials: false
  max-age-seconds: 1800
