apiVersion: v2
name: time-tracking
description: Umbrella Helm chart for the time-tracking platform
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: vault
    version: "~0.28.x"
    repository: https://helm.releases.hashicorp.com
    alias: vault
  - name: auth-service
    version: "0.1.0"
    repository: "file://./auth-service"
  - name: project-service
    version: "0.1.0"
    repository: "file://./project-service"

