tls:
  external:
    name: time-tracking-shared-ca-issuer
    kind: ClusterIssuer

mongodb:
  storage:
    size: 2Gi
  version: "7.0.14"
  rootUser: root
  rootPassword: ""
  username: timetracking
  password: ""
  database: time-tracking

mongodb-operator:
  operator:
    watchNamespace: "*"

postgresql:
  storage:
    size: 2Gi
  database: timetracking
  username: timetracking
  password: ""

cloudnative-pg: { }

auth-service:
  replicaCount: 1
  image:
    repository: time-tracking/auth-service
    registry: ""
    tag: latest
    pullPolicy: IfNotPresent

  config:
    mongoHost: time-tracking-mongodb-svc
    mongoPort: "27017"
    mongoDB: time-tracking
    mongoAuthDB: admin
    mongoSslEnabled: "true"
    vaultUri: https://time-tracking-vault.vault.svc.cluster.local:8200
    vaultKvMount: secret
    vaultSecretPath: auth-service
    authServerIssuer: https://time-tracking-auth-service
    oauth2RedirectUri: http://localhost:3000/callback
    oauth2PostLogoutRedirectUri: http://localhost:3000
    corsAllowedOrigins: http://localhost:3000
    accessTokenTtl: PT1H

  secrets:
    mongoUser: timetracking
    mongoPass: ""
    oauth2ClientId: time-tracking-client

  service:
    type: ClusterIP
    port: 443

  ingress:
    enabled: false
    className: nginx
    host: auth.time-tracking

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

project-service:
  replicaCount: 1
  image:
    repository: time-tracking/project-service
    registry: ""
    tag: latest
    pullPolicy: IfNotPresent

  config:
    dbUrl: "jdbc:postgresql://time-tracking-postgresql-rw:5432/timetracking?ssl=true&sslmode=require"
    vaultUri: https://time-tracking-vault.vault.svc.cluster.local:8200
    vaultKvMount: secret
    vaultSecretPath: project-service
    authServerIssuer: https://time-tracking-auth-service
    authServerJwkSetUri: https://time-tracking-auth-service/oauth2/jwks
    corsAllowedOrigins: http://localhost:3000

  secrets:
    dbUser: timetracking
    dbPass: ""

  service:
    type: ClusterIP
    port: 443

  ingress:
    enabled: false
    className: nginx
    host: api.time-tracking

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

