apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-credentials
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgresql.username | quote }}
  password: {{ .Values.postgresql.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.mongodb.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-root-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.mongodb.rootPassword | quote }}
