{{- $ns  := .Release.Namespace }}
{{- $rel := .Release.Name }}
{{- $issuerName := required "tls.external.name is required for external issuer" .Values.tls.external.name }}
{{- $issuerKind := .Values.tls.external.kind | default "ClusterIssuer" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $rel }}-mongodb-tls
  namespace: {{ $ns }}
spec:
  secretName: {{ $rel }}-mongodb-tls
  duration: 8760h
  renewBefore: 720h
  commonName: {{ $rel }}-mongodb-svc
  dnsNames:
    - {{ $rel }}-mongodb-svc
    - {{ $rel }}-mongodb-svc.{{ $ns }}.svc.cluster.local
    - "*.{{ $rel }}-mongodb-svc.{{ $ns }}.svc.cluster.local"
  issuerRef:
    name: {{ $issuerName }}
    kind: {{ $issuerKind }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $rel }}-auth-service-tls
  namespace: {{ $ns }}
spec:
  secretName: {{ $rel }}-auth-service-tls
  duration: 8760h
  renewBefore: 720h
  commonName: {{ $rel }}-auth-service
  dnsNames:
    - {{ $rel }}-auth-service
    - {{ $rel }}-auth-service.{{ $ns }}.svc.cluster.local
  issuerRef:
    name: {{ $issuerName }}
    kind: {{ $issuerKind }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $rel }}-project-service-tls
  namespace: {{ $ns }}
spec:
  secretName: {{ $rel }}-project-service-tls
  duration: 8760h
  renewBefore: 720h
  commonName: {{ $rel }}-project-service
  dnsNames:
    - {{ $rel }}-project-service
    - {{ $rel }}-project-service.{{ $ns }}.svc.cluster.local
  issuerRef:
    name: {{ $issuerName }}
    kind: {{ $issuerKind }}
